CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    review_id  BIGINT,
    comment    VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE leader
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    job_title  VARCHAR(255),
    CONSTRAINT pk_leader PRIMARY KEY (id)
);

CREATE TABLE reaction
(
    comment_id BIGINT       NOT NULL,
    count      INTEGER,
    emoji      VARCHAR(255) NOT NULL,
    CONSTRAINT pk_reaction PRIMARY KEY (comment_id, emoji)
);

CREATE TABLE review
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating      INTEGER,
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    leader_id   BIGINT,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_REVIEW FOREIGN KEY (review_id) REFERENCES review (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_LEADER FOREIGN KEY (leader_id) REFERENCES leader (id);

ALTER TABLE reaction
    ADD CONSTRAINT fk_reaction_on_comment FOREIGN KEY (comment_id) REFERENCES comment (id);