CREATE SEQUENCE IF NOT EXISTS review_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE if not exists leader
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    job_title  VARCHAR(255),
    CONSTRAINT pk_leader PRIMARY KEY (id)
);

CREATE TABLE if not exists review
(
    id          BIGINT                      NOT NULL,
    rating      INTEGER,
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    leader_id   BIGINT,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_LEADER FOREIGN KEY (leader_id) REFERENCES leader (id);